import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/src/components/theme-provider";
import { AuthProvider } from "@/src/context/auth-context";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Jwsong Portfolio",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.svg",
		apple: {
			url: "/apple-icon.png",
			type: "image/png",
			sizes: "180x180",
		},
		other: [
			{
				rel: "mask-icon",
				url: "/favicon.svg",
				color: "#292524",
			},
		],
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.variable} font-sans bg-[#e4e3df] dark:bg-stone-800 min-h-screen`}>
				<AuthProvider>
					<ThemeProvider>{children}</ThemeProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
